version: '3'

services:
  app:
    build: ./app
    restart: always
    ports:
      - "2368:2368"
    volumes:
      - ./app/content:/var/lib/ghost/content
      - ./app:/app
    env_file:
      - app/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - mysql/.env

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    restart: on-failure
